name: 'Shell Linter'
description: 'Execute lint check on shell scripts using ShellCheck'
author: 'ep-mobile'
inputs:
  path:
    description: 'Execute lint check on a specific file or folder.'
    required: false
    default: '.'
  severity:
    description: 'Specify minimum severity of errors to consider.'
    required: false
    default: 'style'
  exclude-paths:
    description: 'Specify files or folders to exclude during scan.'
    required: false
    default: ''
  exclude-issues:
    description: 'Specify shellcheck issues to exclude during scan.'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.severity }}
    - ${{ inputs.exclude-paths}}
    - ${{ inputs.exclude-issues }}
branding:
  icon: 'check-circle'
  color: 'green'
  